version: '3'

services:

#   Setup node container
  server:
    build: ./server
    expose:
      - "6969"
    environment:
      API_HOST: "http://localhost:6969"
      APP_SERVER_PORT: 6969
    ports:
      - 6969:6969
    volumes:
      - ./server/src:/srv/app/pokemon-app-server/src
    command: node server

#   Setup client container
  server:
    build: ./client
    expose:
      - 3000
    environment:
      - 3000=3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/srv/app/pokemon-app-client/src
      - ./client/public:/srv/app/pokemon-app-client/public
    links:
      - server
    command: yarn start