FROM node:8.7.0-alpine

RUN mkdir -p /srv/app/pokemon-app-server

WORKDIR /srv/app/pokemon-app-server

COPY package*.json /srv/app/pokemon-app-server

RUN npm install

COPY . /srv/app/pokemon-app-server

CMD [ "node", "server" ]